// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:saveday/core/constants/app_env.dart';
/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static final FirebaseOptions web = FirebaseOptions(
    apiKey: AppEnv.API_KEY_WEB,
    appId: AppEnv.APP_ID_WEB,
    messagingSenderId: AppEnv.MESSAGING_SENDER_ID,
    projectId: AppEnv.PROJECT_ID,
    authDomain: AppEnv.AUTH_DOMAIN,
    storageBucket: AppEnv.STORAGE_BUCKET,
  );

  static final FirebaseOptions android = FirebaseOptions(
    apiKey: AppEnv.API_KEY_ANDROID,
    appId: AppEnv.APP_ID_ANDROID,
    messagingSenderId: AppEnv.MESSAGING_SENDER_ID,
    projectId: AppEnv.PROJECT_ID,
    storageBucket: AppEnv.STORAGE_BUCKET,
  );

  static final FirebaseOptions ios = FirebaseOptions(
    apiKey: AppEnv.API_KEY_IOS,
    appId: AppEnv.APP_ID_IOS,
    messagingSenderId: AppEnv.MESSAGING_SENDER_ID,
    projectId: AppEnv.PROJECT_ID,
    storageBucket: AppEnv.STORAGE_BUCKET,
    iosBundleId: AppEnv.IOS_BUNDLE_ID,
  );

  static final FirebaseOptions macos = FirebaseOptions(
    apiKey: AppEnv.API_KEY_MACOS,
    appId: AppEnv.APP_ID_MACOS,
    messagingSenderId: AppEnv.MESSAGING_SENDER_ID,
    projectId: AppEnv.PROJECT_ID,
    storageBucket: AppEnv.STORAGE_BUCKET,
    iosBundleId: AppEnv.IOS_BUNDLE_ID,
  );

  static final FirebaseOptions windows = FirebaseOptions(
    apiKey: AppEnv.API_KEY_WINDOWS,
    appId: AppEnv.APP_ID_WINDOWS,
    messagingSenderId: AppEnv.MESSAGING_SENDER_ID,
    projectId: AppEnv.PROJECT_ID,
    authDomain: AppEnv.AUTH_DOMAIN,
    storageBucket: AppEnv.STORAGE_BUCKET,
  );
}
