// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBI_Ye5cJNeozjVjBjOCAXvfe9E_x52wF8',
    appId: '1:1087801747066:web:ab3c82657af3ec1c52bdc3',
    messagingSenderId: '1087801747066',
    projectId: 'hw-saveday',
    authDomain: 'hw-saveday.firebaseapp.com',
    storageBucket: 'hw-saveday.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBguFojGd0mJ4o5mvKFQRLjEQ2SnSNA9TY',
    appId: '1:1087801747066:android:854beb5b10312a0852bdc3',
    messagingSenderId: '1087801747066',
    projectId: 'hw-saveday',
    storageBucket: 'hw-saveday.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsRFOGEz57t26Jd0d3lHJTBNuMZP4LvdA',
    appId: '1:1087801747066:ios:a24e8a95d60c6dd652bdc3',
    messagingSenderId: '1087801747066',
    projectId: 'hw-saveday',
    storageBucket: 'hw-saveday.firebasestorage.app',
    iosBundleId: 'com.example.saveday',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsRFOGEz57t26Jd0d3lHJTBNuMZP4LvdA',
    appId: '1:1087801747066:ios:a24e8a95d60c6dd652bdc3',
    messagingSenderId: '1087801747066',
    projectId: 'hw-saveday',
    storageBucket: 'hw-saveday.firebasestorage.app',
    iosBundleId: 'com.example.saveday',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBI_Ye5cJNeozjVjBjOCAXvfe9E_x52wF8',
    appId: '1:1087801747066:web:b4d303e59573bdb252bdc3',
    messagingSenderId: '1087801747066',
    projectId: 'hw-saveday',
    authDomain: 'hw-saveday.firebaseapp.com',
    storageBucket: 'hw-saveday.firebasestorage.app',
  );
}
